### ISSUE TITLE
How to build a minimum size container version

### ISSUE THREAD

**Issue by lijiang1983** [OpenTOSCA/container#10]
Dear All:
    I found that container builds multiple versions.
    What is the difference between each version？
    How to build the smallest version？

**Comment by endrescn** [comment]
Hi,
if you refer to the different versions inside of org.opentosca.container.product, they are just for different operating systems. There is no "smallest version", you get always the full OpenTOSCA Container.
Hope that helps you.
Best regards,
Christian
