### ISSUE TITLE
State resource should be aligned to TOSCA

### ISSUE THREAD

**Issue by miwurster** [OpenTOSCA/container#13]
Response of State resource should be aligned to [TOSCA states](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.1/TOSCA-Simple-Profile-YAML-v1.1.html).

**Comment by nyuuyn** [comment]
Those the [initial](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.1/csprd02/TOSCA-Simple-Profile-YAML-v1.1-csprd02.html#_Toc474149652) state imply that the runtime must instantiate the node instances ?

**Comment by miwurster** [comment]
We started a proper state representation with commit 4396b709ca198c714a5e6f5d9c2058593bed6754.
All instance-related resources (Node, ServiceTemplate, Relationship) got a property `state`. The property is a Enum type and uses the proposed states by the TOSCA spec as its base.

**Comment by koppor** [comment]
The possible states are defined in the NodeType (see tab Instance States in
Winery). +1 for default states if no states are defined by the NodeType

Am 30.06.2017 10:23 schrieb "Michael Wurster" <notifications@github.com>:

**Comment by nyuuyn** [comment]
Close ?

**Comment by miwurster** [comment]
Yeah, you are right. Since this has been implemented with 4396b709ca198c714a5e6f5d9c2058593bed6754 we close this issue.
