### ISSUE TITLE
Instance stuck at migration during transformation

### ISSUE THREAD

**Issue by dangpg** [OpenTOSCA/container#131]
**Current Behavior:**
Create two versions of MyTinyToDo_Bare_Docker (one with only DockerEngine, one with DockerEngine and MyTinyToDo), taken from [tosca-definitions-public](https://github.com/OpenTOSCA/tosca-definitions-public/tree/master/servicetemplates/http%253A%252F%252Fopentosca.org%252Fservicetemplates/MyTinyToDo_Bare_Docker).
When transforming a running instance between two different versions of MyTinyToDo_Bare_Docker, transformation fails and instance remains in state **MIGRATING**

**Expected Behavior:**
Old instance has state **MIGRATED** (listed under MyTinyToDo_Bare_Docker_DockerEngine.csar) and new instance is **CREATED** (listed under MyTinyToDo_Bare_Docker_Complete.csar)

**Steps to Reproduce:**
1. Upload both CSARs to Container
2. Create new instance using MyTinyToDo_Bare_Docker_DockerEngine.csar
3. Create transformation plan (POST request to /csars/transform with MyTinyToDo_Bare_Docker_Only_DockerEngine.csar as source and MyTinyToDo_Bare_Docker_Complete.csar as target)
4. Execute transformation plan (listed under instance created in step 2)
5. Transformation is stuck at migration

**Other Information:**
ODE returns the following error message:
```
'//*[local-name()='NodeTemplateInstanceResources']/*[local-name()='NodeTemplateInstances']/*[local-name()='NodeTemplateInstance'][1]/*[local-name()='Links']/*[local-name()='Link']/@*[local-name()='href']/string()' against '<?xml version="1.0" encoding="UTF-8"?>
<NodeTemplateInstanceResources><Links><Link href="http://192.168.2.213:1337/csars/MyTinyToDo_Bare_Docker_DockerEngine.csar/servicetemplates/%257Bhttp%253A%252F%252Fopentosca.org%252Fservicetemplates%257DMyTinyToDo_Bare_Docker_w1-wip1/nodetemplates/DockerEngine/instances" rel="self"/></Links><NodeTemplateInstances/></NodeTemplateInstanceResources>'
```
Performing a GET request to the respective URL returns the DockerEngine node instance with state DELETED

**System Information:**
Operating System: Win10
Container locally hosted using Eclipse (master branch)
Remaining components (UI, engine-plan, ...) run using docker-compose
**CONTAINER_BUS_MANAGEMENT_MOCK set to true**

**Comment by nyuuyn** [comment]
Is fixed in the latest commits, it is also ready for live-modeling now https://github.com/OpenTOSCA/winery/pull/230
