### ISSUE TITLE
Invalid JSON response when requesting NodeTemplate Resource

### ISSUE THREAD

**Issue by dangpg** [OpenTOSCA/container#133]
**Current Behavior:**
Requesting a NodeTemplate Resource returns an invalid JSON response.
In detail, the response contains multiple "_links" entries that are simply empty:

```
[...]
   "interfaces":{
      "interfaces":[
         {
            "name":"ContainerManagementInterface",
            "operations":{},
            "_links"
         },
         {
            "name":"http://opentosca.org/interfaces/connections",
            "operations":{},
            "_links"
         }
      ],
      "_links"
   },
[...]
```

**Expected Behavior:**
Receiving a well-formatted/valid JSON response (e.g. by omitting "_links" or by returning an empty object/array)

**Steps to Reproduce:**
  1. Upload an application to Container
  2. Use Postman to perform GET request (e.g. http://localhost:1337/csars/MyTinyToDo_Bare_Docker.csar/servicetemplates/%257Bhttp%253A%252F%252Fopentosca.org%252Fservicetemplates%257DMyTinyToDo_Bare_Docker/nodetemplates/MyTinyToDoDockerContainer)

**Comment by nyuuyn** [comment]
Is already fixed, empty _links are removed from the response :)
