### ISSUE TITLE
Hibernate.initialize() shouldn't be used

### ISSUE THREAD

**Issue by nyuuyn** [OpenTOSCA/container#148]
**Current Behavior:**
Currently when object can't be loaded in lazy-mode from the databse they are loaded via Hibernate.initialize() method,
see e.g. here:

https://github.com/OpenTOSCA/container/blob/b29cb6c46855e967cbdc3b958ede03290db2f722/org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/repository/ServiceTemplateInstanceRepository.java#L25

**Expected Behavior:**
We shouldn't load objects by relying on underlying implementaion of JPA. A solution would be to deactivate lazy loading via JPA annotations, but then again, we lose lazy loading.

**Comment by Vogel612** [comment]
Eager-Loading of multiple collections attached to the same entity is explicitly not supported by JPA / hibernate. Most likely the correct fix is to enable lazy-loading by changing the lifetime of the used EntityManager from a single method to the lifetime of the Repository Instance.

This would allow lazy loading, making manual eager initialization unnecessary.
