### ISSUE TITLE
Retrieving properties of a service template instance fails occasionally due to blocking transactions

### ISSUE THREAD

**Issue by fakepk** [OpenTOSCA/container#17]
Requesting properties of a service template instance results in following error:
`Response with status: 500 Exception Description: Transaction is currently active for URL: http://localhost:1337/containerapi/CSARs/:id/ServiceTemplates/:templateID/Instances/:instID/Properties`

Just retrieving data from a resource should not trigger a transaction on the database level.

**Comment by nyuuyn** [comment]
Can you reproduce this with the new API? If not => close?
