### ISSUE TITLE
Why is it called container?

### ISSUE THREAD

**Issue by abitrolly** [OpenTOSCA/container#224]
By the source code inside and description, this repo contains an orchestration app, like `terraform` for Terraform and `kubectl` for Kubernetes, or `ansible-playbook` if we talk about Ansible.

But the tool doesn't orchestrate containers, such as Docker, CRI-O, LXD etc. Neither it provides a runtime/VM to run containers in. So why call it container?

**Comment by lharzenetter** [comment]
The name is derived from the old servlet containers. We are already discussing the renaming it as OpenTOSCA Orchestrator internally.
