### ISSUE TITLE
POST operation for deletion of instance

### ISSUE THREAD

**Issue by koppor** [OpenTOSCA/container#23]
Idee: POST {delete} auf servicetemplates/instances. Dann wird termination plan aufgerufen, dann macht der ein DELETE auf servicetemplates/instances/ID

Grund: Wenn man DELETE auf ID macht, wird ein Termination Plan aufgerufen, der (bei Erfolg!) wieder ein DELETE darauf machen müsste. Was bei Miserfolg? -- Also lieber so WSDL-Style mit POST als Command.

**Comment by nyuuyn** [comment]
Already solved.

InstancesResource ist TaskResource für Pläne und diese erstellen und löschen Instanzen, kann entweder auf die Plan State gewartet oder auf das erstellen oder löschen von Instanzen warten via correlation. (Siehe Container Client)
