### ISSUE TITLE
Support Devices for Docker Containers

### ISSUE THREAD

**Issue by milesstoetzner** [OpenTOSCA/container#258]
Should be possible to mount devices into docker containers. 

- [ ] adjust management bus
- [ ] adjust docker container node type
- [ ] adjust docker engine node type
- [ ] write test for starting a container wihtout any mounts
- [ ] write test for starting a container with a mounted device

**Comment by nyuuyn** [comment]
How do you model devices in the topology? Just a property? a whole NodeTemplate?

**Comment by milesstoetzner** [comment]
I would actually model it the same way as docker does. So just as a property.

Besides that I currently do not need this feature so we could close it and open it at a later point.
I thought that I would need it for a use case.
