### ISSUE TITLE
Windows Line Endings throws "No such file or directory" during Execution

### ISSUE THREAD

**Issue by milesstoetzner** [OpenTOSCA/container#259]
If the ScriptArtifact contains windows line endings the execution throws the following error. 

```
�[36mengine-ia-jdk8_1        |�[0m sudo: unable to execute /virtual-Raspberry-Software-Minimal_w1-wip1.csar/artifacttemplates/http%253A%252F%252Fwww.example.org%252Ftosca%252Fartifacttemplates/virtual-ECU-Software-Configure_configure-w1-wip1/files/configure.sh: No such file or directory
```

The error is missleading since the file actually exists but bash can not process it correctly.
We need to discuss how to mitigate this problem.

We could clean the script before execution using e.g. `sed -i -e 's/\r$//' scriptname.sh`.
This only applies to shell scripts.
What is about Python scripts etc.
See https://stackoverflow.com/a/39527986 for more information. 

We could improve logging so that its clear during debugging that the file actually exists and that the problem might indicate a line endings problem. 

We could warn the user in winery that the uploaded script has windows line endings.

What do you think?

----

Tasks

- [x] Docker Container
- [x] Ubuntu VM
- [x] Documentation

**Comment by buehlefs** [comment]
Git can be configured to use the correct line endings even on windows with a `.gitattributes` file in the repository (https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion). The winery could automatically create such a file if it is missing.

**Comment by milesstoetzner** [comment]
We decided to add a dos2unix transformation when transfering the file to the target.
