### ISSUE TITLE
ServiceInstances are not properly deleted after CSAR deletion

### ISSUE THREAD

**Issue by nyuuyn** [OpenTOSCA/container#28]
**Current Behavior:**
If a CSAR is deleted and it has/had running ServiceInstances, the instances won't be deleted. If you reupload the CSAR the ServiceInstance data is back again => no real delete in the backend

**Expected Behavior:**
After deleting a CSAR and reuploading it there shouldn't be any ServiceInstance available afterwards

**Steps to Reproduce:**
  1. Use any CSAR and create an Instance from the Service within (and optionally terminate the instance)
  2. Undeploy the CSAR and redeploy it
  3. You will clearly see that the ServiceInstance from Step 1 is still there

**System Information:**
Issue is independent of Platform

**Comment by miwurster** [comment]
Hey @nyuuyn, is this still an issue?
I don't think so. When I going to terminate an instance, the instance will be updated an has the state `DELETED`. When I trigger the build plan again, a new instance (with new ID) will be created.

**Comment by nyuuyn** [comment]
Suppose all ServiceInstances are DELETED, and then I delete a CSAR, those are not shown anymore. But now I re-deploy the CSAR, the ServiceInstances (in DELETED state) are back. Is this a feature or a bug? :D

**Comment by miwurster** [comment]
Hm, good point. At the moment, our system is designed that this behavior is a feature ;-)

**Comment by nyuuyn** [comment]
Well, then we can close this

**Comment by miwurster** [comment]
Gonna flag it as an enhancement since it's basically a valid improvement ;-)
