### ISSUE TITLE
connectTo gets executed multiple times 

### ISSUE THREAD

**Issue by mar-be** [OpenTOSCA/container#296]
**Current Behavior:**

![grafik](https://user-images.githubusercontent.com/23510257/183888017-99ce9fef-ca6d-4449-a41b-22c3e01a70e6.png)

The `connectTo` operation between the QHana-Backend and the QHana-PluginRunner gets executed twice.
Both times code gets executed at the node of the QHana-Backend.
Once, the QHana-Backend is the source node, and the QHana-PluginRunner is the target node (expected behavior).
Secondly, the QHana-Backend itself is the target node.
The `connectTo` operation has two properties, `IP` and `Port`, that match both nodes, the QHana-Backend and the QHana-PluginRunner.
Presumably, the second execution comes from the other connection between QHana-UI and QHana-Backend.

**Expected Behavior:**

The `connectTo` operation between the QHana-Backend and the QHana-PluginRunner should be executed only once at the QHana-Backend with the QHana-PluginRunner as the target node.

**Comment by nyuuyn** [comment]
wouldn't it be a quick and easy way to solve this to send parameter such as CALLEDASSOURCE=true|false and the IA can determine whether it does something or not ?
