### ISSUE TITLE
Direct file upload via REST doesn't work

### ISSUE THREAD

**Issue by eiselems** [OpenTOSCA/container#5]
Using the direct upload (via Content-Type: Multipart/formdata) a null pointer occurs regardless of the input.

Inside https://github.com/OpenTOSCA/container/blob/master/org.opentosca.containerapi/src/org/opentosca/containerapi/resources/csar/CSARsResource.java

REST-Path:
containerapi/CSARs

**Comment by nyuuyn** [comment]
Hi,

can you post some logs? Or the HTTP Request you are sending to the container?

**Comment by eiselems** [comment]
It seems that the API requires the size information inside the content-disposition.
(as seen inside the Admin UI https://github.com/OpenTOSCA/ui-admin/blob/master/src/main/java/org/opentosca/ui/admin/action/client/ContainerClient.java#L572-575)
