### ISSUE TITLE
local csars were deleted for they were not accessed too long

### ISSUE THREAD

**Issue by aimuke** [OpenTOSCA/container#8]
Hi. 

I'm not so sure whether this is an issue or it is a temp strategy.

Right now, the CSARs will be stored to a temp path(java.io.tmpdir). But the files under temp path will be deleted automatically. For example, in my system, temp files will be deleted if they are not accessed for 10 days. But CSARs are application data, the should not be deleted automatically. Whether the store location  should be changed a new path, so it should not be deleted for unknown?

Regards.

**Comment by nyuuyn** [comment]
Hi,
the container normally uses the system temp folder to store its files, such as CSARs, so yes depending on the system those may be deleted. I've commited (b113338c3918264853770f8a5acb145afa85a52) a work-around, where you can set a VM argument like this: -DopenTOSCAPath=/home/ubuntu. The working dir of the container would than be /home/ubuntu/openTOSCA.

An alternative would be to alter the .product configuration under org.opentosca.container.product or the config.ini in the binary distribution.

Regards

**Comment by aimuke** [comment]
thx it helps a lot.

Regards

**Comment by aimuke** [comment]
Hi,

Another question, there was a startup.sh file in the early version in which i can set the VM argument. But now container is started by a compiled file OpenTOSCA, how should I set the  VM argument DopenTOSCAPath? could you give me some guidance? thx.

Regards.

**Comment by nyuuyn** [comment]
Under {openTOSCARoot}/configuration/config.ini add the following line if you want the container to use the path /home/ubuntu/openTOSCA:
openTOSCAPath=/home/ubuntu

**Comment by aimuke** [comment]
OK, thx.

Regards.
